<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="74372" started-at="2018-06-28T13:46:16Z" finished-at="2018-06-28T13:47:30Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="74372" started-at="2018-06-28T13:46:16Z" finished-at="2018-06-28T13:47:30Z">
      <class name="testSuit.TestPendingPosts">
        <test-method status="FAIL" signature="testApproveFirstTopicFromPendingPostsScreen()[pri:0, instance:testSuit.TestPendingPosts@7d9d1a19]" name="testApproveFirstTopicFromPendingPostsScreen" duration-ms="260" started-at="2018-06-28T19:17:30Z" finished-at="2018-06-28T19:17:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.utilityFunctions.loginUserIfNotLoggedIn(utilityFunctions.java:61)
	at testSuit.TestPendingPosts.testApproveFirstTopicFromPendingPostsScreen(TestPendingPosts.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApproveFirstTopicFromPendingPostsScreen -->
      </class> <!-- testSuit.TestPendingPosts -->
      <class name="testSuit.KnowledgeBaseLoginTest">
        <test-method status="PASS" signature="setupTest()[pri:0, instance:testSuit.KnowledgeBaseLoginTest@5622fdf]" name="setupTest" is-config="true" duration-ms="7040" started-at="2018-06-28T19:16:21Z" finished-at="2018-06-28T19:16:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="setupTest()[pri:0, instance:testSuit.TestHomePage@4883b407]" name="setupTest" is-config="true" duration-ms="842" started-at="2018-06-28T19:16:28Z" finished-at="2018-06-28T19:16:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="setupTest()[pri:0, instance:testSuit.TestPendingPosts@7d9d1a19]" name="setupTest" is-config="true" duration-ms="1151" started-at="2018-06-28T19:16:29Z" finished-at="2018-06-28T19:16:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="testLoginWithValidCredentialsInMobiControl()[pri:1, instance:testSuit.KnowledgeBaseLoginTest@5622fdf]" name="testLoginWithValidCredentialsInMobiControl" duration-ms="14275" started-at="2018-06-28T19:16:30Z" finished-at="2018-06-28T19:16:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithValidCredentialsInMobiControl -->
        <test-method status="PASS" signature="testLoginWithInvalidCrerdentialsInMobicontrol()[pri:2, instance:testSuit.KnowledgeBaseLoginTest@5622fdf]" name="testLoginWithInvalidCrerdentialsInMobicontrol" duration-ms="21794" started-at="2018-06-28T19:16:44Z" finished-at="2018-06-28T19:17:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithInvalidCrerdentialsInMobicontrol -->
      </class> <!-- testSuit.KnowledgeBaseLoginTest -->
      <class name="testSuit.TestHomePage">
        <test-method status="PASS" signature="testExistenceOfFeedbackButton()[pri:1, instance:testSuit.TestHomePage@4883b407]" name="testExistenceOfFeedbackButton" duration-ms="54" started-at="2018-06-28T19:17:06Z" finished-at="2018-06-28T19:17:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExistenceOfFeedbackButton -->
        <test-method status="PASS" signature="validateHomePageTitle()[pri:2, instance:testSuit.TestHomePage@4883b407]" name="validateHomePageTitle" duration-ms="50" started-at="2018-06-28T19:17:06Z" finished-at="2018-06-28T19:17:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageTitle -->
        <test-method status="PASS" signature="testHomePageTabSwitching()[pri:3, instance:testSuit.TestHomePage@4883b407]" name="testHomePageTabSwitching" duration-ms="608" started-at="2018-06-28T19:17:06Z" finished-at="2018-06-28T19:17:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePageTabSwitching -->
        <test-method status="FAIL" signature="testEditDraftCancelOnHomePage()[pri:4, instance:testSuit.TestHomePage@4883b407]" name="testEditDraftCancelOnHomePage" duration-ms="23023" started-at="2018-06-28T19:17:07Z" finished-at="2018-06-28T19:17:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at testSuit.TestHomePage.testEditDraftCancelOnHomePage(TestHomePage.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEditDraftCancelOnHomePage -->
      </class> <!-- testSuit.TestHomePage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
