<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="82469" started-at="2018-06-27T07:14:00Z" finished-at="2018-06-27T07:15:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="82469" started-at="2018-06-27T07:14:00Z" finished-at="2018-06-27T07:15:23Z">
      <class name="testSuit.TestPendingPosts">
        <test-method status="SKIP" signature="testApproveFirstTopicFromPendingPostsScreen()[pri:0, instance:testSuit.TestPendingPosts@6d4b1c02]" name="testApproveFirstTopicFromPendingPostsScreen" duration-ms="23835" started-at="2018-06-27T12:44:13Z" finished-at="2018-06-27T12:44:37Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[No Pending Posts present]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: No Pending Posts present
	at testSuit.TestPendingPosts.testApproveFirstTopicFromPendingPostsScreen(TestPendingPosts.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApproveFirstTopicFromPendingPostsScreen -->
      </class> <!-- testSuit.TestPendingPosts -->
      <class name="testSuit.KnowledgeBaseLoginTest">
        <test-method status="PASS" signature="setupTest()[pri:0, instance:testSuit.KnowledgeBaseLoginTest@6093dd95]" name="setupTest" is-config="true" duration-ms="6354" started-at="2018-06-27T12:44:05Z" finished-at="2018-06-27T12:44:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="setupTest()[pri:0, instance:testSuit.TestHomePage@5622fdf]" name="setupTest" is-config="true" duration-ms="858" started-at="2018-06-27T12:44:11Z" finished-at="2018-06-27T12:44:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="setupTest()[pri:0, instance:testSuit.TestPendingPosts@6d4b1c02]" name="setupTest" is-config="true" duration-ms="1132" started-at="2018-06-27T12:44:12Z" finished-at="2018-06-27T12:44:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="testLoginWithValidCredentialsInMobiControl()[pri:1, instance:testSuit.KnowledgeBaseLoginTest@6093dd95]" name="testLoginWithValidCredentialsInMobiControl" duration-ms="4941" started-at="2018-06-27T12:44:37Z" finished-at="2018-06-27T12:44:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithValidCredentialsInMobiControl -->
        <test-method status="PASS" signature="testLoginWithInvalidCrerdentialsInMobicontrol()[pri:2, instance:testSuit.KnowledgeBaseLoginTest@6093dd95]" name="testLoginWithInvalidCrerdentialsInMobicontrol" duration-ms="21665" started-at="2018-06-27T12:44:42Z" finished-at="2018-06-27T12:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithInvalidCrerdentialsInMobicontrol -->
      </class> <!-- testSuit.KnowledgeBaseLoginTest -->
      <class name="testSuit.TestHomePage">
        <test-method status="PASS" signature="testExistenceOfFeedbackButton()[pri:1, instance:testSuit.TestHomePage@5622fdf]" name="testExistenceOfFeedbackButton" duration-ms="34" started-at="2018-06-27T12:45:03Z" finished-at="2018-06-27T12:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExistenceOfFeedbackButton -->
        <test-method status="PASS" signature="validateHomePageTitle()[pri:2, instance:testSuit.TestHomePage@5622fdf]" name="validateHomePageTitle" duration-ms="51" started-at="2018-06-27T12:45:03Z" finished-at="2018-06-27T12:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageTitle -->
        <test-method status="PASS" signature="testHomePageTabSwitching()[pri:3, instance:testSuit.TestHomePage@5622fdf]" name="testHomePageTabSwitching" duration-ms="534" started-at="2018-06-27T12:45:03Z" finished-at="2018-06-27T12:45:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePageTabSwitching -->
        <test-method status="FAIL" signature="testEditDraftCancelOnHomePage()[pri:4, instance:testSuit.TestHomePage@5622fdf]" name="testEditDraftCancelOnHomePage" duration-ms="18461" started-at="2018-06-27T12:45:04Z" finished-at="2018-06-27T12:45:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at testSuit.TestHomePage.testEditDraftCancelOnHomePage(TestHomePage.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEditDraftCancelOnHomePage -->
      </class> <!-- testSuit.TestHomePage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
